AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    CodeUri: ProjectManagementSystem
    Runtime: java8
    VpcConfig:
      SecurityGroupIds:
        - sg-003b5acd448bc851b
      SubnetIds:
        - subnet-09217d0b8429c6883
        - subnet-01fbf74d74e0211ab
        - subnet-0ef7f64323967edb6
        - subnet-0896207bfef9ad15f
        - subnet-0c9ba8353540d4207
        - subnet-00d516d86d26f7792
    Environment:
      Variables:
        rdsMySqlDatabaseUrl: pms-instance.clce4qi6mzca.us-east-1.rds.amazonaws.com
        dbUsername: admin
        dbPassword: adminpass
Resources:
  AddTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.AddTaskHandler::handleRequest
  AddTeammate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.AddTeammateHandler::handleRequest
  ArchiveProject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.ArchiveProjectHandler::handleRequest
  AssignTeammateToTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.AssignTeammateToTaskHandler::handleRequest
  CreateProject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.CreateProjectHandler::handleRequest
  DecomposeTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.DecomposeTaskHandler::handleRequest
  DeleteProject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.DeleteProjectHandler::handleRequest
  ListAllProjects:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.ListAllProjectsHandler::handleRequest
  MarkTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.MarkTaskHandler::handleRequest
  RemoveTeammate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.RemoveTeammateHandler::handleRequest
  RenameTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.RenameTaskHandler::handleRequest
  UnassignTeammateFromTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: arobgrab.UnassignTeammateFromTaskHandler::handleRequest
