AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        rdsMySqlDatabaseUrl: pms-instance.clce4qi6mzca.us-east-1.rds.amazonaws.com
        dbUsername: admin
        dbPassword: adminpass
Resources:
  AddTask:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Runtime: java8
      Handler: arobgrab.AddTaskHandler::handleRequest
  AddTeammate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.AddTeammateHandler::handleRequest
      Runtime: java8
  ArchiveProject:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.ArchiveProjectHandler::handleRequest
      Runtime: java8
  AssignTeammateToTask:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.AssignTeammateToTaskHandler::handleRequest
      Runtime: java8
  CreateProject:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.CreateProjectHandler::handleRequest
      Runtime: java8
  DecomposeTask:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.DecomposeTaskHandler::handleRequest
      Runtime: java8
  DeleteProject:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.DeleteProjectHandler::handleRequest
      Runtime: java8
  ListAllProjects:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.ListAllProjectsHandler::handleRequest
      Runtime: java8
  MarkTask:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.MarkTaskHandler::handleRequest
      Runtime: java8
  RemoveTeammate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.RemoveTeammateHandler::handleRequest
      Runtime: java8
  RenameTask:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.RenameTaskHandler::handleRequest
      Runtime: java8
  UnassignTeammateFromTask:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProjectManagementSystem
      Handler: arobgrab.UnassignTeammateFromTaskHandler::handleRequest
      Runtime: java8
